### ISSUE TITLE
Build on launchpad is not generating man page

### ISSUE THREAD

**Issue by x4121** [x4121/ripgrep-ubuntu#1]
Even when `asciidoc` is specified as build dependency, launchpad is not generating the man page. `ubuntu:xenial` docker container with build dependencies builds everything correctly when running `debuild -us -uc`

**Comment by BurntSushi** [comment]
This is the place where ripgrep generates the man page: https://github.com/BurntSushi/ripgrep/blob/d18839f3dcf7d599dc96f8ee36627d7b97d234b8/build.rs#L71-L108 --- Note that it requires the `a2x` binary, which is purportedly part of `asciidoc`.

For debugging, you can look for the output of the build script like so:

```
$ dir="$(dirname "$(find ./target/release -name stderr -print0 | xargs -0 ls -t | head -n1)")"
$ echo $dir
./target/release/build/ripgrep-1cbf390b18878233
$ cat $dir/output
cargo:rustc-env=RIPGREP_BUILD_GIT_HASH=afde6ee395
$ cat $dir/stderr
$
```

**Comment by x4121** [comment]
Hi and thanks for the reply :slightly_smiling_face: 
Sadly just adding `asciidoc` as a build dependency didn't work (see `https://github.com/x4121/ripgrep-ubuntu/commit/651bd144dc89ddd284c04556d7391e81b6ce8605` and resulting log `https://launchpadlibrarian.net/385409785/buildlog_ubuntu-xenial-amd64.ripgrep_0.9.0-1_BUILDING.txt.gz`).

I have no real way to simulate what Launchpad is doing during build/prebuild steps currently. I might need to take a deeper look into that, to find out why `a2x` is not available during build :confused:

**Comment by BurntSushi** [comment]
@x4121 Weird. Note that ripgrep's own CI uses Ubuntu, and it builds a man page. My comments suggest all of these were required to get it to work: https://github.com/BurntSushi/ripgrep/blob/3edeeca6e94b4e812b4ff078cf92f3178436daa3/.travis.yml#L10-L14

**Comment by x4121** [comment]
Thanks. Will try this when I get home tonight. Maybe my testing environment in docker installed some recommended packages that the one on Launchpad didn't

**Comment by x4121** [comment]
Thanks, some missing dependencies (that I somehow had in my otherwise new docker container) were the issue :slightly_smiling_face:
